version: "3.7"

x-common:
  &common-settings
  build:
    context: .
    dockerfile: docker/Dockerfile
  restart: always

services:
  web:
    << : *common-settings
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
    tty: true
    stdin_open: true

  db:
    image: postgres:12-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

networks:
  backend:
    external: true
